# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83a4d13841db66400865caaaf391fa3d0ffb6df2b219b94fc191a81bffd3b11946585e52889b297adafc6bf3089e801ba84cde2f34b83f04e09b4bfc9978fe92

test:
  secret_key_base: c738610fa8f7d1396b491f5b7a76e958fecf10417803e0f2d47f68c73d121242cf27bba8b932fea58e655c8b4f37b0d51fb7c26e12cc4aca2fc3fb474d758d8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
